export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_IMG = 'SET_IMG';

export const FETCH_SERVER_START = 'FETCH_SERVER_START';
export const FETCH_SERVER_SUCCESS = 'FETCH_SERVER_SUCCESS';
export const FETCH_SERVER_FAIL = 'FETCH_SERVER_FAIL';

export const AUTHENTICATE_THE_USER = 'AUTHENTICATE_THE_USER';